### PR TITLE
Added TypeScript type definitions.

### PR DESCRIPTION
**Pull request by mrhornsby**
* Added TypeScript type definition: lib/step.d.ts
* Updated devDependencies as advised by `npm audit` (mocha had critical and high vulnerabilities)
* Bumped version to 1.2.0 (return type change warrants a minor bump rather than a patch?)

### CODE REVIEW

**Comment by rprieto** [comment]
Hi, thanks for the PR! The type definitions and dependency upgrades look good.

I don't understand though why we need to duplicate all tests as `.ts`? I think the behaviour is unchanged.

**Comment by mrhornsby** [comment]
^ Fixed a filename and reference in package.json - didn't affect the tests, but would have caused issues when using the package as a dependency. This is now working. I don't anticipate any more changes.

**Comment by mrhornsby** [comment]
> Hi, thanks for the PR! The type definitions and dependency upgrades look good.
> 
> I don't understand though why we need to duplicate all tests as `.ts`? I think the behaviour is unchanged.

Hi, we don't necessarily need to duplicate them all, it just confirms that the TypeScript definitions work for all the test cases you currently have. (In theory you could delete the javascript tests as the TS files just compile down and get tested in the same way - it just depends if you want any future tests to be written in TypeScript). Happy to remove or change things, just let me know what you prefer 😉

**Comment by rprieto** [comment]
I think this package will stay written in raw JS for now. Very happy to add TypeScript definitions for people to easily use it from TypeScript projects :+1:

I still don't understand why we need tests in `.ts`. The tests verify the behaviour of the package. Would the TypeScript tests catch anything that the JS tests don't catch? For example, would they fail if the type definitions were wrong? If that's the case, I think it should be enough to add a single `.ts` file that checks 2 small examples, rather than duplicate the whole test suite.

**Comment by mrhornsby** [comment]
> I still don't understand why we need tests in `.ts`. The tests verify the behaviour of the package. Would the TypeScript tests catch anything that the JS tests don't catch? For example, would they fail if the type definitions were wrong? If that's the case, I think it should be enough to add a single `.ts` file that checks 2 small examples, rather than duplicate the whole test suite.

Yes, they would fail to compile (and therefore the test fails). Good idea - I'll reduce it to just one test file with cases that prove the definitions.

**Comment by mrhornsby** [comment]
Hi, now a single test file with one test for each of `step` and `xstep`. A lot cleaner. Let me know what you think. Mark

**Comment by rprieto** [comment]
Perfect, I agree it looks very clean. I'll try to publish a new version shortly !
Thanks again for the TypeScript support.

**Comment by mrhornsby** [comment]
No worries, thanks for the library, glad I could contribute something useful!

**Comment by rprieto** [comment]
I just published `v1.3.0`. Let me know if it worked!

**Pull request merged**
